# Generated by Django 5.2.3 on 2026-04-26 09:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLatestEpisodeId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeId', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Minister_title', models.CharField(max_length=200)),
                ('company_church', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(help_text='Full professional biography')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('expertise', models.JSONField(default=list)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastestEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('guestSpeaker', models.CharField(max_length=40)),
                ('publicationDate', models.DateTimeField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('episode_num', models.IntegerField()),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('authorAvatar', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SlideshowsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImage', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
                ('topic', models.CharField(blank=True, default='NA', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('itemImage', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
                ('ratings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('countInStock', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('numReviews', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=200)),
                ('lastName', models.CharField(default='', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subscribType', models.CharField(default='', max_length=200)),
                ('startedDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=25)),
                ('timeStamped', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPublication', models.CharField(blank=True, max_length=12)),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeId', models.IntegerField(default=api.models.get_next_episode_id, editable=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('air_Date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('media_url', models.URLField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('images', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
                ('slideImage', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guests_array', models.ManyToManyField(blank=True, to='api.guestspeaker')),
            ],
        ),
    ]
