# Generated by Django 5.2.3 on 2026-04-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastestepisodes',
            name='guestSpeaker',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
