# Generated by Django 5.2.3 on 2025-06-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listofsubscribers',
            old_name='started_date',
            new_name='startedDate',
        ),
    ]
