# Generated by Django 5.2.3 on 2026-04-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lastestepisodes_guestspeaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastestepisodes',
            name='guestSpeaker',
        ),
        migrations.AddField(
            model_name='lastestepisodes',
            name='guestSpeaker',
            field=models.ManyToManyField(blank=True, to='api.guestspeaker'),
        ),
    ]
