# Generated by Django 5.2.3 on 2025-07-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_started_date_listofsubscribers_starteddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfScripturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
