# Generated by Django 5.2.3 on 2025-07-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_listofscripturepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='listofscripturepost',
            name='message',
            field=models.TextField(),
        ),
    ]
