# Generated by Django 5.2.3 on 2025-07-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_storeproductitems_alter_listofscripturepost_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfScripturePost',
            new_name='ListOfScripture',
        ),
    ]
