# Generated by Django 5.2.3 on 2025-07-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_listofscripturepost_listofscripture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=25)),
                ('timeStamped', models.DateTimeField()),
            ],
        ),
    ]
