# Generated by Django 5.2.3 on 2025-08-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_themecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductitems',
            name='itemImage',
            field=models.ImageField(blank=True, default='fallback.JPEG', upload_to=''),
        ),
    ]
