# Generated by Django 5.2.3 on 2025-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_storeproductitems_itemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPublication', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='storeproductitems',
            name='itemImage',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
    ]
