# Generated by Django 5.2.3 on 2025-09-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_upcomingevents_alter_storeproductitems_itemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('authorAvatar', models.ImageField(default='fallback.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SlideshowsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImage', models.ImageField(blank=True, default='fallback.jsp', upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='ListOfSubscribers',
            new_name='SubscribersList',
        ),
        migrations.DeleteModel(
            name='ListOfScripture',
        ),
    ]
