# Generated by Django 5.2.3 on 2025-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_scripturelist_slideshowsimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowsimage',
            name='topic',
            field=models.CharField(blank=True, default='NA', max_length=300),
        ),
    ]
