# Generated by Django 5.2.3 on 2025-09-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_slideshowsimage_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshowsimage',
            name='topic',
        ),
    ]
