# Generated by Django 5.2.3 on 2025-09-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_slideshowsimage_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowsimage',
            name='topic',
            field=models.CharField(blank=True, default='NA', max_length=300),
        ),
    ]
