# Generated by Django 5.2.3 on 2025-09-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_slideshowsimage_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowsimage',
            name='sliderImage',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
    ]
