# Generated by Django 5.2.3 on 2025-09-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_slideshowsimage_sliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripturelist',
            name='authorAvatar',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
    ]
