# Generated by Django 5.2.3 on 2025-09-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_scripturelist_authoravatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripturelist',
            name='authorAvatar',
        ),
        migrations.RemoveField(
            model_name='scripturelist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scripturelist',
            name='topic',
        ),
    ]
