# Generated by Django 5.2.3 on 2025-09-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_scripturelist_authoravatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripturelist',
            name='authorAvatar',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='scripturelist',
            name='category',
            field=models.CharField(default=20250102, max_length=100),
            preserve_default=False,
        ),
    ]
