# Generated by Django 5.2.3 on 2025-09-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_scripturelist_authoravatar_scripturelist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductitems',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
