# Generated by Django 5.2.3 on 2025-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_storeproductitems_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevents',
            name='dateOfPublication',
            field=models.CharField(max_length=12),
        ),
    ]
