# Generated by Django 5.2.3 on 2025-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_upcomingevents_dateofpublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberslist',
            name='firstName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriberslist',
            name='lastName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriberslist',
            name='subscribType',
            field=models.CharField(default='', max_length=200),
        ),
    ]
