# Generated by Django 5.2.3 on 2025-10-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_subscriberslist_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductitems',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storeproductitems',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storeproductitems',
            name='countInStock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='storeproductitems',
            name='numReviews',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
