# Generated by Django 5.2.3 on 2025-11-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_storeproductitems_brand_storeproductitems_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastestEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('summary', models.CharField(max_length=65)),
                ('guestSpeaker', models.CharField(max_length=20)),
                ('publicationDate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storeproductitems',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storeproductitems',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
