# Generated by Django 5.2.3 on 2025-11-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_lastestepisodes_alter_storeproductitems_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastestepisodes',
            name='thumbnail',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='lastestepisodes',
            name='guestSpeaker',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='lastestepisodes',
            name='summary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lastestepisodes',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
