# Generated by Django 5.2.3 on 2025-11-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_lastestepisodes_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductitems',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storeproductitems',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
