# Generated by Django 5.2.3 on 2025-11-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_storeproductitems_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductitems',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
