# Generated by Django 5.2.3 on 2025-11-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_storeproductitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevents',
            name='dateOfPublication',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='topic',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
