# Generated by Django 5.2.3 on 2025-12-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_upcomingevents_dateofpublication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberslist',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
