# Generated by Django 5.2.3 on 2026-01-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_subscriberslist_enddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLatestEpisodeId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeId', models.CharField(blank=True)),
            ],
        ),
    ]
