# Generated by Django 5.2.3 on 2026-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_firstlatestepisodeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
