# Generated by Django 5.2.3 on 2026-04-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_upcomingevents_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('bio', models.TextField(help_text='Full professional biography')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('expertise', models.JSONField(default=list)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeId', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('air_Date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('media_url', models.URLField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('images', models.ImageField(blank=True, default='fallback.jpg', upload_to='')),
                ('guests_array', models.ManyToManyField(blank=True, to='api.guestspeaker')),
            ],
        ),
    ]
