# Generated by Django 5.2.3 on 2026-04-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_guestspeaker_episode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestspeaker',
            old_name='job_title',
            new_name='Minister_title',
        ),
    ]
