# Generated by Django 5.2.3 on 2026-04-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_job_title_guestspeaker_minister_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestspeaker',
            name='company',
        ),
        migrations.AddField(
            model_name='guestspeaker',
            name='company_church',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='guestspeaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
